### ISSUE TITLE
Kasban - Bad Request

### ISSUE THREAD

**Issue by shanefits** [SmoofCreative/kasban#269]
When I hit the Authenticate button on Kasban I get a Bad Request page back from the server with the following shown on the screen:

**Error**

invalid_request: The `redirect_uri` parameter does not match a valid url for the application.

**Comment by S-Denaro** [comment]
I have the same exact problem. Did you find any solution?

**Comment by shanefits** [comment]
No solution to date S-Denaro - no response from the developers yet either!
I've tried to work around it by using Asana Connect but no success there.

**Comment by alexdunne** [comment]
Hey both, sorry this isn't working for you.

The project has be deprecated in favour of [Asana boards](https://asana.com/guide/help/views/boards).
